import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from "@/contexts/authContext";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

function Header() {
  return (
    <header className="p-4 bg-gray-100 shadow-sm">
      <nav className="flex gap-4">
        <Link href="/data" className="hover:underline">
          Data
        </Link>
        <Link href="/admin" className="hover:underline">
          Admin
        </Link>
      </nav>
    </header>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
